method: onet_depth
data:
  path: data/ShapeNet.depth
  img_folder: img
  img_size: 224 
  points_subsample: 2048 
  points_unpackbits: false
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256
  z_dim: 0
training:
  out_dir:  out/img_depth/onet_depth
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  #loss_type: cross_entropy_with_sigmoid
  visualize_every: 10000
  validate_every: 10000
  backup_every: 20000
  phase: 2
  detach: true
  depth_map_mix: false
test:
  threshold: 0.4
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

