method: onet
data:
  path: data/ShapeNet.new3
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: 2048 
  points_unpackbits: false
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256
  z_dim: 0
training:
  out_dir:  out/img/onet_sigmoid_newdata
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  loss_type: l2
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.6
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

