method: onet_m
data:
  path: data/ShapeNet
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: 2048 
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256
  z_dim: 0
training:
  out_dir:  out/img/onet_m
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
  stop_category_loss_epoch: 100
  calc_feature_category_loss: false
  record_feature_category: true
  attractive_p: 0.001
  repulsive_p: 0.1
  feature_k: 0.1
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

