method: onet
data:
  path: ./data/ShapeNet.with_depth.10w10w/
  #input_range: [0, 150000]
  #test_range: [0, 100000]
  img_folder: img
  input_type: img
  img_extension: png
  img_size: 224 
  points_subsample: 2048 
  points_unpackbits: true
  train_split: updated_train
  val_split: updated_val
  test_split: updated_test
  points_file: points_direct_tsdf0.008.npz
  points_iou_file: points_direct_tsdf0.008.npz
  train_tsdf: 0.002
  test_tsdf: 0.002
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256
  z_dim: 0
training:
  out_dir:  out/img_depth_uniform/onet
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
  backup_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  generation_dir: generation_simplify
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2
  refinement_step: 30
  simplify_nfaces: 10000
