method: onet_multi_layers
data:
  path: /home3/data/xieyunwei/occnet_data/ShapeNet.without_fusion
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: 2048 
  points_unpackbits: false
model:
  encoder_latent: null
  decoder: cbatchnorm2
  decoder_kwargs:
    n_blocks: 2
  encoder: full
  c_dim: 256
  z_dim: 0
training:
  out_dir:  out/img_without_fusion/onet_multi_layer_full
  batch_size: 48
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.4
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

