data_parallel: null
method: SAL
data:
  dataset: Shapes3D_list
  train_instance_list: 03636649/train_instance.lst
  input_type: null
  input_fields: ['pointcloud']
  test_instance_list: null
  val_instance_list: null
  path: /home3/xieyunwei/ShapeNet.SAL
  points_subsample: null
  points_file: sal_30000.npz
  with_transforms: false
  pointcloud_file: pointcloud_fps_N30000.npz
  pointcloud_n: null
  pointcloud_noise: null
model:
  encoder_latent: null
  decoder: deepsdf
  decoder_kwargs:
    dims: [512, 512, 512, 512, 512, 512, 512, 512]
    dropout: []
    dropout_prob: 0.2
    norm_layers: [0, 1, 2, 3, 4, 5, 6, 7]
    latent_in: [4]
    xyz_in_all: False
    activation: null
    latent_dropout: False
    weight_norm: True
    initial_radius: 0.4
  encoder: null
  c_dim: 0
  z_dim: 0
training:
  out_dir:  out/sal/z0/all_class_training_schedule/03636649/
  batch_size: 1
  model_selection_metric: loss
  model_selection_mode: minimize
  checkpoint_every: 10000
  validate_every: 10000
  backup_every: 20000
  visualize_every: 5000
  print_every: 10
  exit_after: 150000
  surface_point_weight: 0.5
test:
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt
generation:
  generation_dir: generation_150000
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 256
  upsampling_steps: 0
  furthur_refine: false
  #refinement_step: 30
  simplify_nfaces: 30000
  




